# Generated by Django 5.1.4 on 2026-05-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='locked_for_audit',
            field=models.BooleanField(default=False),
        ),
    ]
