services:
  - type: web
    name: breathe-esg-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: breathe-esg-lhb2.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://breathe-esg-dun.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: breathe-esg-db
          property: connectionString

  - type: web
    name: breathe-esg-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://breathe-esg-lhb2.onrender.com/api

databases:
  - name: breathe-esg-db
    plan: free
